# This is a basic workflow to help you get started with Actions

name: Deployment to Repsy

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Bintray
        uses: simontunnat/action-maven-deploy@v1
        with:
          username: ${{ secrets.REPSY_USERNAME }}
          password: ${{ secrets.REPSY_PASSWORD }}
          repository: ${{ secrets.REPSY_REPOSITORY }}
