# This is a basic workflow to help you get started with Actions

name: Deployment to Repsy

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Release to Repsy
        uses: qcastel/github-actions-maven-release@master
        with:
          release-branch-name: "master"
          maven-repo-server-id: "repsy"
          maven-repo-server-username: ${{ secrets.REPSY_USERNAME }}
          maven-repo-server-password: ${{ secrets.REPSY_PASSWORD }}
          git-release-bot-name: "release-bot"
          git-release-bot-email: "jurica1.migac@gmail.com"
          access-token: ${{ secrets.RELEASE_PAT_TOKEN }}
